gridmap_updater_node:
  ros__parameters:
    use_sim_time: true
    camera_info_topic: /zed2/zed_node/wild/camera_info
    camera_topic: /zed2/zed_node/wild/image_rect_color
    # lidar_topic: /front_laser/points
    lidar_topic: /cloud_segmentation_tconcord3d/points
    map_frame: map
    robot_frame: base_link
    camera_frame: zed2_wild
