name: humble

on:
  pull_request:
    branches:
      - humble
  push:
    branches:
      - humble
      
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
      fail-fast: false
    steps:
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.7.1
        with:
          required-ros-distributions: humble
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.3.5
        with:
          package-name: local_navigation
          target-ros2-distro: humble
          vcs-repo-file-url: ${GITHUB_WORKSPACE}/dependencies.repos
      - name: Codecov
        uses: codecov/codecov-action@v1.2.1
        with:
          file: ros_ws/lcov/total_coverage.info
          flags: unittests
          name: codecov-umbrella
          # yml: ./codecov.yml
          fail_ci_if_error: false
